// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlawLP-tJXzSXjenatyD3vXlPCMI0DrHA',
    appId: '1:1090697424609:web:a313516a8d813c0ae851a0',
    messagingSenderId: '1090697424609',
    projectId: 'netflixpro-12dfc',
    authDomain: 'netflixpro-12dfc.firebaseapp.com',
    storageBucket: 'netflixpro-12dfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHTZwPFfpmxh76UzcetGPT_BQrCAEAGh4',
    appId: '1:1090697424609:android:6145c638842595f2e851a0',
    messagingSenderId: '1090697424609',
    projectId: 'netflixpro-12dfc',
    storageBucket: 'netflixpro-12dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsVaHu09gOhUGv4OQyggx1zH1fT3w6lPA',
    appId: '1:1090697424609:ios:1bfefc2214e4ea02e851a0',
    messagingSenderId: '1090697424609',
    projectId: 'netflixpro-12dfc',
    storageBucket: 'netflixpro-12dfc.firebasestorage.app',
    iosBundleId: 'com.example.netflixpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsVaHu09gOhUGv4OQyggx1zH1fT3w6lPA',
    appId: '1:1090697424609:ios:1bfefc2214e4ea02e851a0',
    messagingSenderId: '1090697424609',
    projectId: 'netflixpro-12dfc',
    storageBucket: 'netflixpro-12dfc.firebasestorage.app',
    iosBundleId: 'com.example.netflixpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlawLP-tJXzSXjenatyD3vXlPCMI0DrHA',
    appId: '1:1090697424609:web:1834b58ce51e8088e851a0',
    messagingSenderId: '1090697424609',
    projectId: 'netflixpro-12dfc',
    authDomain: 'netflixpro-12dfc.firebaseapp.com',
    storageBucket: 'netflixpro-12dfc.firebasestorage.app',
  );
}
